export const functions = [
  "approve(address,uint256)",
  "balanceOf(address)",
  "baseExtension()",
  "baseHiddenUri()",
  "baseTokenURI()",
  "baseURI()",
  "getApproved(uint256)",
  "isApprovedForAll(address,address)",
  "maxMints()",
  "maxSupply()",
  "merkleRoot()",
  "mint(uint256)",
  "mintAvailable()",
  "mintRate()",
  "name()",
  "owner()",
  "ownerOf(uint256)",
  "publicSale()",
  "renounceOwnership()",
  "revealed()",
  "safeTransferFrom(address,address,uint256)",
  "safeTransferFrom(address,address,uint256,bytes)",
  "setApprovalForAll(address,bool)",
  "setBaseHiddenUri(string)",
  "setBaseURI(string)",
  "setMaxMints(uint256)",
  "setMaxSupply(uint256)",
  "setMerkleRoot(bytes32)",
  "setMintRate(uint256)",
  "setWhiteListMaxMints(uint256)",
  "setWhitelistMintRate(uint256)",
  "supportsInterface(bytes4)",
  "symbol()",
  "togglePublicSale()",
  "toggleReveal()",
  "toggleWhitelistSale()",
  "tokenURI(uint256)",
  "totalSupply()",
  "transferFrom(address,address,uint256)",
  "transferOwnership(address)",
  "usedAddresses(address)",
  "whiteListMaxMints()",
  "whiteListMint(uint256,bytes32[])",
  "whiteListUsedAddresses(address)",
  "whitelistMintRate()",
  "whitelistSale()",
  "withdraw()",
];

export const mock = {
  interface: {
    fragments: [
      {
        name: null,
        type: "constructor",
        inputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "error",
        name: "ApprovalCallerNotOwnerNorApproved",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "ApprovalQueryForNonexistentToken",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "ApprovalToCurrentOwner",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "ApproveToCaller",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "BalanceQueryForZeroAddress",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "ExceededLimit",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "InvalidMerkle",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "MintToZeroAddress",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "MintZeroQuantity",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "NotEnoughTokensLeft",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "OwnerQueryForNonexistentToken",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "PublicSaleNotLive",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "TransferCallerNotOwnerNorApproved",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "TransferFromIncorrectOwner",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "TransferToNonERC721ReceiverImplementer",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "TransferToZeroAddress",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "URIQueryForNonexistentToken",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "WhitelistNotActive",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "WhitelistUsed",
        inputs: [],
        _isFragment: true,
      },
      {
        type: "error",
        name: "WrongEther",
        inputs: [],
        _isFragment: true,
      },
      {
        name: "Approval",
        anonymous: false,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "approved",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      {
        name: "ApprovalForAll",
        anonymous: false,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "approved",
            type: "bool",
            indexed: false,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      {
        name: "OwnershipTransferred",
        anonymous: false,
        inputs: [
          {
            name: "previousOwner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "newOwner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      {
        name: "Transfer",
        anonymous: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      {
        type: "function",
        name: "approve",
        constant: false,
        inputs: [
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "balanceOf",
        constant: true,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "baseExtension",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "baseHiddenUri",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "baseTokenURI",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "baseURI",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "getApproved",
        constant: true,
        inputs: [
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "isApprovedForAll",
        constant: true,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "maxMints",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "maxSupply",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "merkleRoot",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bytes32",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes32",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "mint",
        constant: false,
        inputs: [
          {
            name: "quantity",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: true,
        stateMutability: "payable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "mintAvailable",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "mintRate",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "name",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "owner",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "ownerOf",
        constant: true,
        inputs: [
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "publicSale",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "renounceOwnership",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "revealed",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "safeTransferFrom",
        constant: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "safeTransferFrom",
        constant: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
          {
            name: "_data",
            type: "bytes",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setApprovalForAll",
        constant: false,
        inputs: [
          {
            name: "operator",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "approved",
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setBaseHiddenUri",
        constant: false,
        inputs: [
          {
            name: "_baseHiddenUri",
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setBaseURI",
        constant: false,
        inputs: [
          {
            name: "_newBaseURI",
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setMaxMints",
        constant: false,
        inputs: [
          {
            name: "_newMaxMints",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setMaxSupply",
        constant: false,
        inputs: [
          {
            name: "_newSupply",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setMerkleRoot",
        constant: false,
        inputs: [
          {
            name: "_root",
            type: "bytes32",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes32",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setMintRate",
        constant: false,
        inputs: [
          {
            name: "_mintRate",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setWhiteListMaxMints",
        constant: false,
        inputs: [
          {
            name: "_newWhiteListMaxMints",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "setWhitelistMintRate",
        constant: false,
        inputs: [
          {
            name: "_mintRate",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "supportsInterface",
        constant: true,
        inputs: [
          {
            name: "interfaceId",
            type: "bytes4",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes4",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "symbol",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "togglePublicSale",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "toggleReveal",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "toggleWhitelistSale",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "tokenURI",
        constant: true,
        inputs: [
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "totalSupply",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "transferFrom",
        constant: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "transferOwnership",
        constant: false,
        inputs: [
          {
            name: "newOwner",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "usedAddresses",
        constant: true,
        inputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "whiteListMaxMints",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "whiteListMint",
        constant: false,
        inputs: [
          {
            name: "quantity",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
          {
            name: "proof",
            type: "bytes32[]",
            indexed: null,
            components: null,
            arrayLength: -1,
            arrayChildren: {
              name: null,
              type: "bytes32",
              indexed: null,
              components: null,
              arrayLength: null,
              arrayChildren: null,
              baseType: "bytes32",
              _isParamType: true,
            },
            baseType: "array",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: true,
        stateMutability: "payable",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "whiteListUsedAddresses",
        constant: true,
        inputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "whitelistMintRate",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "whitelistSale",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      {
        type: "function",
        name: "withdraw",
        constant: false,
        inputs: [],
        outputs: [],
        payable: true,
        stateMutability: "payable",
        gas: null,
        _isFragment: true,
      },
    ],
    _abiCoder: {
      coerceFunc: null,
    },
    functions: {
      "approve(address,uint256)": {
        type: "function",
        name: "approve",
        constant: false,
        inputs: [
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "balanceOf(address)": {
        type: "function",
        name: "balanceOf",
        constant: true,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "baseExtension()": {
        type: "function",
        name: "baseExtension",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "baseHiddenUri()": {
        type: "function",
        name: "baseHiddenUri",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "baseTokenURI()": {
        type: "function",
        name: "baseTokenURI",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "baseURI()": {
        type: "function",
        name: "baseURI",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "getApproved(uint256)": {
        type: "function",
        name: "getApproved",
        constant: true,
        inputs: [
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "isApprovedForAll(address,address)": {
        type: "function",
        name: "isApprovedForAll",
        constant: true,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "maxMints()": {
        type: "function",
        name: "maxMints",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "maxSupply()": {
        type: "function",
        name: "maxSupply",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "merkleRoot()": {
        type: "function",
        name: "merkleRoot",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bytes32",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes32",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "mint(uint256)": {
        type: "function",
        name: "mint",
        constant: false,
        inputs: [
          {
            name: "quantity",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: true,
        stateMutability: "payable",
        gas: null,
        _isFragment: true,
      },
      "mintAvailable()": {
        type: "function",
        name: "mintAvailable",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "mintRate()": {
        type: "function",
        name: "mintRate",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "name()": {
        type: "function",
        name: "name",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "owner()": {
        type: "function",
        name: "owner",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "ownerOf(uint256)": {
        type: "function",
        name: "ownerOf",
        constant: true,
        inputs: [
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "publicSale()": {
        type: "function",
        name: "publicSale",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "renounceOwnership()": {
        type: "function",
        name: "renounceOwnership",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "revealed()": {
        type: "function",
        name: "revealed",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "safeTransferFrom(address,address,uint256)": {
        type: "function",
        name: "safeTransferFrom",
        constant: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "safeTransferFrom(address,address,uint256,bytes)": {
        type: "function",
        name: "safeTransferFrom",
        constant: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
          {
            name: "_data",
            type: "bytes",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setApprovalForAll(address,bool)": {
        type: "function",
        name: "setApprovalForAll",
        constant: false,
        inputs: [
          {
            name: "operator",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "approved",
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setBaseHiddenUri(string)": {
        type: "function",
        name: "setBaseHiddenUri",
        constant: false,
        inputs: [
          {
            name: "_baseHiddenUri",
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setBaseURI(string)": {
        type: "function",
        name: "setBaseURI",
        constant: false,
        inputs: [
          {
            name: "_newBaseURI",
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setMaxMints(uint256)": {
        type: "function",
        name: "setMaxMints",
        constant: false,
        inputs: [
          {
            name: "_newMaxMints",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setMaxSupply(uint256)": {
        type: "function",
        name: "setMaxSupply",
        constant: false,
        inputs: [
          {
            name: "_newSupply",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setMerkleRoot(bytes32)": {
        type: "function",
        name: "setMerkleRoot",
        constant: false,
        inputs: [
          {
            name: "_root",
            type: "bytes32",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes32",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setMintRate(uint256)": {
        type: "function",
        name: "setMintRate",
        constant: false,
        inputs: [
          {
            name: "_mintRate",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setWhiteListMaxMints(uint256)": {
        type: "function",
        name: "setWhiteListMaxMints",
        constant: false,
        inputs: [
          {
            name: "_newWhiteListMaxMints",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "setWhitelistMintRate(uint256)": {
        type: "function",
        name: "setWhitelistMintRate",
        constant: false,
        inputs: [
          {
            name: "_mintRate",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "supportsInterface(bytes4)": {
        type: "function",
        name: "supportsInterface",
        constant: true,
        inputs: [
          {
            name: "interfaceId",
            type: "bytes4",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bytes4",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "symbol()": {
        type: "function",
        name: "symbol",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "togglePublicSale()": {
        type: "function",
        name: "togglePublicSale",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "toggleReveal()": {
        type: "function",
        name: "toggleReveal",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "toggleWhitelistSale()": {
        type: "function",
        name: "toggleWhitelistSale",
        constant: false,
        inputs: [],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "tokenURI(uint256)": {
        type: "function",
        name: "tokenURI",
        constant: true,
        inputs: [
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "string",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "string",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "totalSupply()": {
        type: "function",
        name: "totalSupply",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "transferFrom(address,address,uint256)": {
        type: "function",
        name: "transferFrom",
        constant: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "transferOwnership(address)": {
        type: "function",
        name: "transferOwnership",
        constant: false,
        inputs: [
          {
            name: "newOwner",
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        gas: null,
        _isFragment: true,
      },
      "usedAddresses(address)": {
        type: "function",
        name: "usedAddresses",
        constant: true,
        inputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "whiteListMaxMints()": {
        type: "function",
        name: "whiteListMaxMints",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "whiteListMint(uint256,bytes32[])": {
        type: "function",
        name: "whiteListMint",
        constant: false,
        inputs: [
          {
            name: "quantity",
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
          {
            name: "proof",
            type: "bytes32[]",
            indexed: null,
            components: null,
            arrayLength: -1,
            arrayChildren: {
              name: null,
              type: "bytes32",
              indexed: null,
              components: null,
              arrayLength: null,
              arrayChildren: null,
              baseType: "bytes32",
              _isParamType: true,
            },
            baseType: "array",
            _isParamType: true,
          },
        ],
        outputs: [],
        payable: true,
        stateMutability: "payable",
        gas: null,
        _isFragment: true,
      },
      "whiteListUsedAddresses(address)": {
        type: "function",
        name: "whiteListUsedAddresses",
        constant: true,
        inputs: [
          {
            name: null,
            type: "address",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "whitelistMintRate()": {
        type: "function",
        name: "whitelistMintRate",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "uint256",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "whitelistSale()": {
        type: "function",
        name: "whitelistSale",
        constant: true,
        inputs: [],
        outputs: [
          {
            name: null,
            type: "bool",
            indexed: null,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        payable: false,
        stateMutability: "view",
        gas: null,
        _isFragment: true,
      },
      "withdraw()": {
        type: "function",
        name: "withdraw",
        constant: false,
        inputs: [],
        outputs: [],
        payable: true,
        stateMutability: "payable",
        gas: null,
        _isFragment: true,
      },
    },
    errors: {
      "ApprovalCallerNotOwnerNorApproved()": {
        type: "error",
        name: "ApprovalCallerNotOwnerNorApproved",
        inputs: [],
        _isFragment: true,
      },
      "ApprovalQueryForNonexistentToken()": {
        type: "error",
        name: "ApprovalQueryForNonexistentToken",
        inputs: [],
        _isFragment: true,
      },
      "ApprovalToCurrentOwner()": {
        type: "error",
        name: "ApprovalToCurrentOwner",
        inputs: [],
        _isFragment: true,
      },
      "ApproveToCaller()": {
        type: "error",
        name: "ApproveToCaller",
        inputs: [],
        _isFragment: true,
      },
      "BalanceQueryForZeroAddress()": {
        type: "error",
        name: "BalanceQueryForZeroAddress",
        inputs: [],
        _isFragment: true,
      },
      "ExceededLimit()": {
        type: "error",
        name: "ExceededLimit",
        inputs: [],
        _isFragment: true,
      },
      "InvalidMerkle()": {
        type: "error",
        name: "InvalidMerkle",
        inputs: [],
        _isFragment: true,
      },
      "MintToZeroAddress()": {
        type: "error",
        name: "MintToZeroAddress",
        inputs: [],
        _isFragment: true,
      },
      "MintZeroQuantity()": {
        type: "error",
        name: "MintZeroQuantity",
        inputs: [],
        _isFragment: true,
      },
      "NotEnoughTokensLeft()": {
        type: "error",
        name: "NotEnoughTokensLeft",
        inputs: [],
        _isFragment: true,
      },
      "OwnerQueryForNonexistentToken()": {
        type: "error",
        name: "OwnerQueryForNonexistentToken",
        inputs: [],
        _isFragment: true,
      },
      "PublicSaleNotLive()": {
        type: "error",
        name: "PublicSaleNotLive",
        inputs: [],
        _isFragment: true,
      },
      "TransferCallerNotOwnerNorApproved()": {
        type: "error",
        name: "TransferCallerNotOwnerNorApproved",
        inputs: [],
        _isFragment: true,
      },
      "TransferFromIncorrectOwner()": {
        type: "error",
        name: "TransferFromIncorrectOwner",
        inputs: [],
        _isFragment: true,
      },
      "TransferToNonERC721ReceiverImplementer()": {
        type: "error",
        name: "TransferToNonERC721ReceiverImplementer",
        inputs: [],
        _isFragment: true,
      },
      "TransferToZeroAddress()": {
        type: "error",
        name: "TransferToZeroAddress",
        inputs: [],
        _isFragment: true,
      },
      "URIQueryForNonexistentToken()": {
        type: "error",
        name: "URIQueryForNonexistentToken",
        inputs: [],
        _isFragment: true,
      },
      "WhitelistNotActive()": {
        type: "error",
        name: "WhitelistNotActive",
        inputs: [],
        _isFragment: true,
      },
      "WhitelistUsed()": {
        type: "error",
        name: "WhitelistUsed",
        inputs: [],
        _isFragment: true,
      },
      "WrongEther()": {
        type: "error",
        name: "WrongEther",
        inputs: [],
        _isFragment: true,
      },
    },
    events: {
      "Approval(address,address,uint256)": {
        name: "Approval",
        anonymous: false,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "approved",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      "ApprovalForAll(address,address,bool)": {
        name: "ApprovalForAll",
        anonymous: false,
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "approved",
            type: "bool",
            indexed: false,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "bool",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      "OwnershipTransferred(address,address)": {
        name: "OwnershipTransferred",
        anonymous: false,
        inputs: [
          {
            name: "previousOwner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "newOwner",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
      "Transfer(address,address,uint256)": {
        name: "Transfer",
        anonymous: false,
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "address",
            _isParamType: true,
          },
          {
            name: "tokenId",
            type: "uint256",
            indexed: true,
            components: null,
            arrayLength: null,
            arrayChildren: null,
            baseType: "uint256",
            _isParamType: true,
          },
        ],
        type: "event",
        _isFragment: true,
      },
    },
    structs: {},
    deploy: {
      name: null,
      type: "constructor",
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      gas: null,
      _isFragment: true,
    },
    _isInterface: true,
  },
  provider: null,
  signer: null,
  callStatic: {},
  estimateGas: {},
  functions: {},
  populateTransaction: {},
  filters: {},
  _runningEvents: {},
  _wrappedEmits: {},
  address: "0xDAA87A5d8036347Ec796F994861B4BE466E2C997",
  resolvedAddress: {},
};
